apiVersion: batch/v1
kind: Job
metadata:
  name: moj-ucsd
spec:
  template:
    spec:
      containers:
      - name: moj-container
        image: jaehyuncha/moj:latest
        command: ["python", "/app/src/buzzBench/chat_completion_Buzzbench.py"]
        resources:
          limits:
            nvidia.com/gpu: 1
      restartPolicy: Never
